### ISSUE TITLE
[BUG] Cannot goto a specific line in Remote Mode

### ISSUE THREAD

**Issue by AStupidBear** [JunoLab/Juno.jl#290]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.35.1
- Julia version: 1.1
- OS: Windows
- Package versions:
  - Atom.jl: 0.8.4
  - julia-client: 0.8.2
  - ink: 0.10.3

![tmp](https://user-images.githubusercontent.com/16422976/56113948-fc577f00-5f91-11e9-89f2-fef182b9a7a2.gif)

You can see, Juno just opened that file but couldn't go to line 102

**Comment by pfitzseb** [comment]
Should be fixed by now.

**Comment by AStupidBear** [comment]
> Should be fixed by now.

If that's fixed, could you tag a new release? Neither `apm update` or `Pkg.update()` showed nothing.

**Comment by pfitzseb** [comment]
Yeah, I was trying to get the release out last evening, but there's a weird test failure that's holding everything up. Sorry!

**Comment by AStupidBear** [comment]
@pfitzseb The problem is still there after updating atom-julia-client, ink, Atom.jl, Juno.jl

![tmp](https://user-images.githubusercontent.com/16422976/58484822-708e6080-8195-11e9-852e-3677af76d608.gif)

**Comment by pfitzseb** [comment]
Should be fixed for good with https://github.com/JunoLab/atom-ink/commit/312b3e3107e2474c6bebb00f92b201754ec35a9c.
